// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: activation.proto
#include "stdafx.h"
#include "activation.pb.h"
#include "activation.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace service {

static const char* MT4Callback_method_names[] = {
  "/service.MT4Callback/Activation",
  "/service.MT4Callback/Price",
};

std::unique_ptr< MT4Callback::Stub> MT4Callback::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MT4Callback::Stub> stub(new MT4Callback::Stub(channel));
  return stub;
}

MT4Callback::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Activation_(MT4Callback_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Price_(MT4Callback_method_names[1], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::service::ActivationReq, ::service::NullResp>* MT4Callback::Stub::ActivationRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::service::ActivationReq, ::service::NullResp>::Create(channel_.get(), rpcmethod_Activation_, context);
}

::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>* MT4Callback::Stub::AsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::ActivationReq, ::service::NullResp>::Create(channel_.get(), cq, rpcmethod_Activation_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>* MT4Callback::Stub::PrepareAsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::ActivationReq, ::service::NullResp>::Create(channel_.get(), cq, rpcmethod_Activation_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::service::PriceReq, ::service::NullResp>* MT4Callback::Stub::PriceRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::service::PriceReq, ::service::NullResp>::Create(channel_.get(), rpcmethod_Price_, context);
}

::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>* MT4Callback::Stub::AsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::PriceReq, ::service::NullResp>::Create(channel_.get(), cq, rpcmethod_Price_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>* MT4Callback::Stub::PrepareAsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::service::PriceReq, ::service::NullResp>::Create(channel_.get(), cq, rpcmethod_Price_, context, false, nullptr);
}

MT4Callback::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MT4Callback_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< MT4Callback::Service, ::service::ActivationReq, ::service::NullResp>(
          std::mem_fn(&MT4Callback::Service::Activation), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MT4Callback_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< MT4Callback::Service, ::service::PriceReq, ::service::NullResp>(
          std::mem_fn(&MT4Callback::Service::Price), this)));
}

MT4Callback::Service::~Service() {
}

::grpc::Status MT4Callback::Service::Activation(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::ActivationReq>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MT4Callback::Service::Price(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::PriceReq>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace service

