// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: activation.proto
#ifndef GRPC_activation_2eproto__INCLUDED
#define GRPC_activation_2eproto__INCLUDED

#include "activation.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace service {

class MT4Callback final {
 public:
  static constexpr char const* service_full_name() {
    return "service.MT4Callback";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>> Activation(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>>(ActivationRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>> AsyncActivation(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>>(AsyncActivationRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>> PrepareAsyncActivation(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>>(PrepareAsyncActivationRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::service::PriceReq, ::service::NullResp>> Price(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::service::PriceReq, ::service::NullResp>>(PriceRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>> AsyncPrice(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>>(AsyncPriceRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>> PrepareAsyncPrice(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>>(PrepareAsyncPriceRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>* ActivationRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>* AsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::service::ActivationReq, ::service::NullResp>* PrepareAsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::service::PriceReq, ::service::NullResp>* PriceRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>* AsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::service::PriceReq, ::service::NullResp>* PrepareAsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::service::ActivationReq, ::service::NullResp>> Activation(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::service::ActivationReq, ::service::NullResp>>(ActivationRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>> AsyncActivation(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>>(AsyncActivationRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>> PrepareAsyncActivation(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>>(PrepareAsyncActivationRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::service::PriceReq, ::service::NullResp>> Price(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::service::PriceReq, ::service::NullResp>>(PriceRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>> AsyncPrice(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>>(AsyncPriceRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>> PrepareAsyncPrice(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>>(PrepareAsyncPriceRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::service::ActivationReq, ::service::NullResp>* ActivationRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>* AsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::service::ActivationReq, ::service::NullResp>* PrepareAsyncActivationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::service::PriceReq, ::service::NullResp>* PriceRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>* AsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::service::PriceReq, ::service::NullResp>* PrepareAsyncPriceRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Activation_;
    const ::grpc::internal::RpcMethod rpcmethod_Price_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Activation(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::ActivationReq>* stream);
    virtual ::grpc::Status Price(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::PriceReq>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Activation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Activation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Activation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Activation(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::ActivationReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestActivation(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::service::NullResp, ::service::ActivationReq>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Price : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Price() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Price() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Price(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::PriceReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrice(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::service::NullResp, ::service::PriceReq>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Activation<WithAsyncMethod_Price<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Activation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Activation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Activation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Activation(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::ActivationReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Price : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Price() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Price() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Price(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service::NullResp, ::service::PriceReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace service


#endif  // GRPC_activation_2eproto__INCLUDED
