// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: activation.proto
#ifndef GRPC_activation_2eproto__INCLUDED
#define GRPC_activation_2eproto__INCLUDED

#include "activation.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace service {

class MT4Callback final {
 public:
  static constexpr char const* service_full_name() {
    return "service.MT4Callback";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Activation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::service::NullResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>> AsyncActivation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>>(AsyncActivationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>> PrepareAsyncActivation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>>(PrepareAsyncActivationRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>* AsyncActivationRaw(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::NullResp>* PrepareAsyncActivationRaw(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Activation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::service::NullResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::NullResp>> AsyncActivation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::NullResp>>(AsyncActivationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::NullResp>> PrepareAsyncActivation(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::NullResp>>(PrepareAsyncActivationRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::service::NullResp>* AsyncActivationRaw(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::NullResp>* PrepareAsyncActivationRaw(::grpc::ClientContext* context, const ::service::ActivationReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Activation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Activation(::grpc::ServerContext* context, const ::service::ActivationReq* request, ::service::NullResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Activation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Activation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Activation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Activation(::grpc::ServerContext* context, const ::service::ActivationReq* request, ::service::NullResp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestActivation(::grpc::ServerContext* context, ::service::ActivationReq* request, ::grpc::ServerAsyncResponseWriter< ::service::NullResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Activation<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Activation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Activation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Activation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Activation(::grpc::ServerContext* context, const ::service::ActivationReq* request, ::service::NullResp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Activation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Activation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::service::ActivationReq, ::service::NullResp>(std::bind(&WithStreamedUnaryMethod_Activation<BaseClass>::StreamedActivation, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Activation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Activation(::grpc::ServerContext* context, const ::service::ActivationReq* request, ::service::NullResp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedActivation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::service::ActivationReq,::service::NullResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Activation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Activation<Service > StreamedService;
};

}  // namespace service


#endif  // GRPC_activation_2eproto__INCLUDED
